// Type-only re-exports of the Anchor IDL JSON for the four production
// programs. The JSON files are generated by `anchor idl build` against the
// on-chain programs (see commit history in `packages/programs-core`); v1
// IDLs are hand-edited until the toolchain stabilises.
//
// IDL spec: 0.1.0 (Anchor 0.30+ format). Compatible with `@coral-xyz/anchor`
// 0.30.x at runtime.

import soothAmmIdl from "./sooth_amm.json" with { type: "json" };
import soothMarketIdl from "./sooth_market.json" with { type: "json" };
import soothLaunchpadIdl from "./sooth_launchpad.json" with { type: "json" };
import soothAdjudicatorIdl from "./sooth_adjudicator.json" with { type: "json" };

export { soothAmmIdl, soothMarketIdl, soothLaunchpadIdl, soothAdjudicatorIdl };

// Looser typed re-export — Anchor consumes `Idl`, the JSON-parsed shape is
// structurally compatible.
export type SoothAmmIdl = typeof soothAmmIdl;
export type SoothMarketIdl = typeof soothMarketIdl;
export type SoothLaunchpadIdl = typeof soothLaunchpadIdl;
export type SoothAdjudicatorIdl = typeof soothAdjudicatorIdl;
