// Type-only re-exports of the Anchor IDL JSON for `sooth_amm` and
// `sooth_market`. The JSON files are generated by `anchor idl build` against
// the on-chain programs (see commit history in `packages/programs-core`).
//
// IDL spec: 0.1.0 (Anchor 0.30+ format). Compatible with `@coral-xyz/anchor`
// 0.30.x at runtime.

import soothAmmIdl from "./sooth_amm.json" with { type: "json" };
import soothMarketIdl from "./sooth_market.json" with { type: "json" };

export { soothAmmIdl, soothMarketIdl };

// Looser typed re-export — Anchor consumes `Idl`, the JSON-parsed shape is
// structurally compatible.
export type SoothAmmIdl = typeof soothAmmIdl;
export type SoothMarketIdl = typeof soothMarketIdl;
